# Generated by Django 4.2 on 2023-07-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_image_techslides_techsheet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechSlides',
            new_name='TechSlide',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['category', 'name']},
        ),
    ]
